name = "boilerplate-test"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
pages_build_output_dir = "./dist"

[vars]
project_access_key = "oesk7yu5tjNfQElu5HjuUunAAAAAAAAAA"
evm_private_key = "0xc3589f265112772f87f4cc48492a4fd821f8769b66dc97d921692c329ba31fc4"
chain = "arbitrum-sepolia"

[[d1_databases]]
binding = "DB"
database_name = "boilerplates-db"
database_id = "364bf9bc-b2ab-4e2d-a2bb-ded003e653ed"

[dev]
port = 4444